export const dummyResources = [
  {
    id: '1',
    title: 'The Odin Project – Full-Stack Web Dev Curriculum',
    url: 'https://www.theodinproject.com',
    category: 'Web Dev',
    description:
      'A free, open-source curriculum to learn full-stack web development from scratch — HTML, CSS, JavaScript, Node, and React included.',
    upvote_count: 312,
    user_id: 'user-1',
    created_at: '2026-05-01T08:00:00Z',
    profiles: { name: 'Jainul Abdeen', image: null },
  },
  {
    id: '2',
    title: 'javascript.info – The Modern JavaScript Tutorial',
    url: 'https://javascript.info',
    category: 'Web Dev',
    description:
      'Comprehensive guide covering JS basics to advanced topics like async/await, Promises, closures, and the DOM — beautifully written.',
    upvote_count: 278,
    user_id: 'user-2',
    created_at: '2026-05-03T10:00:00Z',
    profiles: { name: 'Priya Sharma', image: null },
  },
  {
    id: '3',
    title: 'CSS-Tricks – A Complete Guide to Flexbox',
    url: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
    category: 'Web Dev',
    description:
      'The definitive visual reference for CSS Flexbox. Every property explained with diagrams. Bookmark it forever.',
    upvote_count: 245,
    user_id: 'user-3',
    created_at: '2026-05-05T09:30:00Z',
    profiles: { name: 'Aditya Kumar', image: null },
  },
  {
    id: '4',
    title: 'Next.js Docs – App Router Guide',
    url: 'https://nextjs.org/docs/app',
    category: 'Web Dev',
    description:
      'Official Next.js documentation for the App Router — Server Components, Layouts, Actions, and everything new in Next 13+.',
    upvote_count: 198,
    user_id: 'user-1',
    created_at: '2026-05-08T14:00:00Z',
    profiles: { name: 'Jainul Abdeen', image: null },
  },
  {
    id: '5',
    title: 'NeetCode 150 – Blind 75 Structured Roadmap',
    url: 'https://neetcode.io/practice',
    category: 'Data Structures',
    description:
      'Structured DSA practice by NeetCode — 150 curated LeetCode problems grouped by pattern with video explanations for each.',
    upvote_count: 421,
    user_id: 'user-4',
    created_at: '2026-04-20T07:00:00Z',
    profiles: { name: 'Rohan Mehta', image: null },
  },
  {
    id: '6',
    title: 'Visualgo – Visualize Data Structures & Algorithms',
    url: 'https://visualgo.net/en',
    category: 'Data Structures',
    description:
      'Interactive animations of sorting, trees, graphs, heaps, and more. Perfect for building intuition before coding.',
    upvote_count: 360,
    user_id: 'user-5',
    created_at: '2026-04-22T11:00:00Z',
    profiles: { name: 'Sneha Patel', image: null },
  },
  {
    id: '7',
    title: 'GeeksForGeeks – DSA Self-Paced Course (Free)',
    url: 'https://www.geeksforgeeks.org/data-structures/',
    category: 'Data Structures',
    description:
      'Comprehensive free articles and problems on arrays, linked lists, trees, graphs, tries, and segment trees.',
    upvote_count: 290,
    user_id: 'user-6',
    created_at: '2026-04-25T13:00:00Z',
    profiles: { name: 'Karan Singh', image: null },
  },
  {
    id: '8',
    title: 'CP Algorithms – Competitive Programming Algorithms',
    url: 'https://cp-algorithms.com',
    category: 'Algorithms',
    description:
      'In-depth explanations and C++ implementations of algorithms used in competitive programming — from basic sorting to advanced graph theory.',
    upvote_count: 334,
    user_id: 'user-7',
    created_at: '2026-04-18T09:00:00Z',
    profiles: { name: 'Ananya Reddy', image: null },
  },
  {
    id: '9',
    title: 'MIT OpenCourseWare – Introduction to Algorithms (6.006)',
    url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    category: 'Algorithms',
    description:
      'Free lecture notes, problem sets, and exams from MIT\'s flagship algorithms course. World-class content, zero cost.',
    upvote_count: 305,
    user_id: 'user-8',
    created_at: '2026-04-15T12:00:00Z',
    profiles: { name: 'Vikram Nair', image: null },
  },
  {
    id: '10',
    title: 'fast.ai – Practical Deep Learning for Coders',
    url: 'https://course.fast.ai',
    category: 'Machine Learning',
    description:
      'A top-down, practical approach to deep learning using PyTorch. Start coding real models in lesson 1 — no PhD required.',
    upvote_count: 389,
    user_id: 'user-9',
    created_at: '2026-04-10T10:00:00Z',
    profiles: { name: 'Divya Iyer', image: null },
  },
  {
    id: '11',
    title: 'Machine Learning Mastery – Jason Brownlee',
    url: 'https://machinelearningmastery.com',
    category: 'Machine Learning',
    description:
      'Hands-on tutorials in Python covering scikit-learn, Keras, PyTorch, and XGBoost — great for applied ML beginners.',
    upvote_count: 271,
    user_id: 'user-2',
    created_at: '2026-04-12T08:00:00Z',
    profiles: { name: 'Priya Sharma', image: null },
  },
  {
    id: '12',
    title: 'Andrej Karpathy – Neural Networks: Zero to Hero (YouTube)',
    url: 'https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ',
    category: 'Machine Learning',
    description:
      'Build GPT from scratch, understand backprop and micrograd — one of the clearest ML video series by the ex-Tesla AI director.',
    upvote_count: 518,
    user_id: 'user-10',
    created_at: '2026-04-05T14:00:00Z',
    profiles: { name: 'Arjun Das', image: null },
  },
  {
    id: '13',
    title: 'Khan Academy – Physics (Mechanics, Waves, Electricity)',
    url: 'https://www.khanacademy.org/science/physics',
    category: 'Physics',
    description:
      'Free, structured physics lessons with practice problems and videos. Covers Newtonian mechanics, thermodynamics, and more.',
    upvote_count: 210,
    user_id: 'user-11',
    created_at: '2026-04-28T09:00:00Z',
    profiles: { name: 'Meera Krishnan', image: null },
  },
  {
    id: '14',
    title: 'HyperPhysics – Georgia State University',
    url: 'http://hyperphysics.phy-astr.gsu.edu/hbase/index.html',
    category: 'Physics',
    description:
      'Concept maps linking every physics topic from classical mechanics to quantum theory. Ideal for exam prep and quick reference.',
    upvote_count: 187,
    user_id: 'user-12',
    created_at: '2026-04-30T11:00:00Z',
    profiles: { name: 'Suresh Babu', image: null },
  },
  {
    id: '15',
    title: '3Blue1Brown – Essence of Linear Algebra (YouTube)',
    url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab',
    category: 'Mathematics',
    description:
      'Visual, intuitive explanations of vectors, matrices, eigenvalues, and transformations. Geometry of linear algebra finally clicks.',
    upvote_count: 495,
    user_id: 'user-9',
    created_at: '2026-03-20T10:00:00Z',
    profiles: { name: 'Divya Iyer', image: null },
  },
  {
    id: '16',
    title: 'Paul\'s Online Math Notes – Calculus I, II, III',
    url: 'https://tutorial.math.lamar.edu',
    category: 'Mathematics',
    description:
      'University-level calculus notes with worked examples, practice problems, and cheat sheets. Students swear by it.',
    upvote_count: 342,
    user_id: 'user-3',
    created_at: '2026-03-25T08:00:00Z',
    profiles: { name: 'Aditya Kumar', image: null },
  },
  {
    id: '17',
    title: 'Brilliant.org – Interactive Math & CS Courses',
    url: 'https://brilliant.org',
    category: 'Mathematics',
    description:
      'Problem-first learning for math, logic, algorithms, and CS. Some courses are free — great for building problem-solving intuition.',
    upvote_count: 220,
    user_id: 'user-5',
    created_at: '2026-04-01T09:00:00Z',
    profiles: { name: 'Sneha Patel', image: null },
  },
  {
    id: '18',
    title: 'Use The Index, Luke! – SQL Indexing and Performance',
    url: 'https://use-the-index-luke.com',
    category: 'Database',
    description:
      'Developer-focused guide to SQL indexing, query optimization, and performance. Language-agnostic and deeply practical.',
    upvote_count: 268,
    user_id: 'user-6',
    created_at: '2026-04-08T12:00:00Z',
    profiles: { name: 'Karan Singh', image: null },
  },
  {
    id: '19',
    title: 'CMU Database Systems (15-445) – Free Lectures',
    url: 'https://15445.courses.cs.cmu.edu/fall2023/',
    category: 'Database',
    description:
      'Andy Pavlo\'s legendary database systems course — covers storage, indexing, query execution, concurrency, and recovery.',
    upvote_count: 317,
    user_id: 'user-7',
    created_at: '2026-03-15T10:00:00Z',
    profiles: { name: 'Ananya Reddy', image: null },
  },
  {
    id: '20',
    title: 'Docker – Official Getting Started Guide',
    url: 'https://docs.docker.com/get-started/',
    category: 'DevOps',
    description:
      'The official, hands-on Docker tutorial — containers, images, volumes, and compose. Start here before Kubernetes.',
    upvote_count: 256,
    user_id: 'user-1',
    created_at: '2026-04-14T13:00:00Z',
    profiles: { name: 'Jainul Abdeen', image: null },
  },
  {
    id: '21',
    title: 'roadmap.sh – DevOps Learning Roadmap',
    url: 'https://roadmap.sh/devops',
    category: 'DevOps',
    description:
      'Community-maintained visual roadmap for DevOps engineers — Linux, networking, CI/CD, containers, cloud, and monitoring.',
    upvote_count: 301,
    user_id: 'user-4',
    created_at: '2026-04-16T11:00:00Z',
    profiles: { name: 'Rohan Mehta', image: null },
  },
  {
    id: '22',
    title: 'GitHub Actions – Official Quickstart',
    url: 'https://docs.github.com/en/actions/quickstart',
    category: 'DevOps',
    description:
      'Build and deploy CI/CD pipelines directly in GitHub. This quickstart gets your first workflow running in minutes.',
    upvote_count: 189,
    user_id: 'user-8',
    created_at: '2026-04-19T09:00:00Z',
    profiles: { name: 'Vikram Nair', image: null },
  },
  {
    id: '23',
    title: 'Flutter – Official Codelabs & Documentation',
    url: 'https://docs.flutter.dev/codelabs',
    category: 'Mobile Dev',
    description:
      'Hands-on codelabs from Google for building beautiful native apps in Flutter. Works on iOS, Android, and the web.',
    upvote_count: 234,
    user_id: 'user-10',
    created_at: '2026-04-24T10:00:00Z',
    profiles: { name: 'Arjun Das', image: null },
  },
  {
    id: '24',
    title: 'React Native – Official Tutorial (Expo)',
    url: 'https://reactnative.dev/docs/tutorial',
    category: 'Mobile Dev',
    description:
      'Learn React Native from the official docs. Build cross-platform mobile apps with JavaScript and React knowledge you already have.',
    upvote_count: 212,
    user_id: 'user-11',
    created_at: '2026-04-26T12:00:00Z',
    profiles: { name: 'Meera Krishnan', image: null },
  },
  {
    id: '25',
    title: 'Grokking System Design Interview – Educative',
    url: 'https://www.educative.io/courses/grokking-the-system-design-interview',
    category: 'System Design',
    description:
      'The go-to resource for cracking system design rounds — URL shortener, Twitter, Netflix, and more with architecture diagrams.',
    upvote_count: 447,
    user_id: 'user-12',
    created_at: '2026-03-10T09:00:00Z',
    profiles: { name: 'Suresh Babu', image: null },
  },
  {
    id: '26',
    title: 'System Design Primer – GitHub (donnemartin)',
    url: 'https://github.com/donnemartin/system-design-primer',
    category: 'System Design',
    description:
      'The most starred system design repo on GitHub — covers scalability, CAP theorem, load balancing, caching, databases, and more.',
    upvote_count: 513,
    user_id: 'user-2',
    created_at: '2026-03-05T08:00:00Z',
    profiles: { name: 'Priya Sharma', image: null },
  },
  {
    id: '27',
    title: 'ByteByteGo – System Design Newsletter',
    url: 'https://bytebytego.com',
    category: 'System Design',
    description:
      'Visual system design explanations by Alex Xu, author of "System Design Interview." Free weekly newsletter and YouTube channel.',
    upvote_count: 398,
    user_id: 'user-3',
    created_at: '2026-03-12T10:00:00Z',
    profiles: { name: 'Aditya Kumar', image: null },
  },
  {
    id: '28',
    title: 'Regex101 – Online Regex Tester and Debugger',
    url: 'https://regex101.com',
    category: 'Other',
    description:
      'Test and debug regular expressions live with explanations for each token. Supports JavaScript, Python, PHP, and more.',
    upvote_count: 175,
    user_id: 'user-5',
    created_at: '2026-05-10T11:00:00Z',
    profiles: { name: 'Sneha Patel', image: null },
  },
  {
    id: '29',
    title: 'Excalidraw – Virtual Collaborative Whiteboard',
    url: 'https://excalidraw.com',
    category: 'Other',
    description:
      'Free, open-source sketching tool for drawing system diagrams, flowcharts, and architecture sketches with a hand-drawn feel.',
    upvote_count: 143,
    user_id: 'user-6',
    created_at: '2026-05-12T14:00:00Z',
    profiles: { name: 'Karan Singh', image: null },
  },
  {
    id: '30',
    title: 'freeCodeCamp – Full Stack Development Certification',
    url: 'https://www.freecodecamp.org/learn',
    category: 'Web Dev',
    description:
      'Free 3,000-hour curriculum covering HTML, CSS, JavaScript, React, Node.js, APIs, and databases with projects and certifications.',
    upvote_count: 367,
    user_id: 'user-7',
    created_at: '2026-05-14T09:00:00Z',
    profiles: { name: 'Ananya Reddy', image: null },
  },
];
